### ISSUE TITLE
函数或变量 'DVO_mexMEX' 无法识别

### ISSUE THREAD

**Issue by Sun-199801** [Sangluisme/MultiviewLightEnhancedDepthSR#2]
您好！我想请问一下我已经将MEX插件安装上，并且测试成功，为什么运行主函数还是会出现 “函数或变量 'DVO_mexMEX' 无法识别”这个问题？

**Comment by Sangluisme** [comment]
Please check after you make the cpp file, if the mex file is generated in cpp build bin folder, then please add the folder to your Matlab path.
